### ISSUE TITLE
As a developer I want the main Program to be modular through configuration.

### ISSUE THREAD

**Issue by nshCore** [catalyst-network/Catalyst#141]
- [ ] - delete all module and settings overrides
- [x] - allow debug flag
- [x] - remove os detection part of #78
- [ ] - remove network override 
- [ ] - remove node option builder 
- [ ] - remove kernel builder
- [ ] - remove daemon mode
