### ISSUE TITLE
As a node I want to be able to ping a node on the network.

### ISSUE THREAD

**Issue by nshCore** [catalyst-network/Catalyst#176]
- [ ] create udp message with 0/1 for ping/ping
- [x] define message format
- [x] message should contain a correlation ID
- [ ] node sending ping should be able to store correlation Id 
- [ ] node replying should return same correlation ID
- [ ] node receiving response should be able to match correlation Id with the initial one sent~
- [ ] If node does not receive a response it should de-rep that node
- [ ] if it receives a response with an un-matched correlation Id message should be discarded and offending node de-valued.
